import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PropertyReportData, Photo } from './reportDataCollector';

interface TableOfContentsEntry {
  title: string;
  page: number;
}

export class CaptureProReportGenerator {
  private doc: jsPDF;
  private currentPage: number = 1;
  private tableOfContents: TableOfContentsEntry[] = [];
  private appendixPhotos: Array<{ photo: Photo; reference: string }> = [];
  private readonly pageWidth = 210;
  private readonly pageHeight = 297;
  private readonly margin = 20;
  private readonly contentWidth = 170;
  private totalOriginalSize: number = 0;
  private totalCompressedSize: number = 0;

  constructor() {
    this.doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
  }

  async generateReport(data: PropertyReportData): Promise<Blob> {
    console.log('[PDF] Starting report generation for property:', data.property.job_reference);

    console.log('[PDF] Creating cover page...');
    await this.createCoverPage(data);

    console.log('[PDF] Creating table of contents placeholder...');
    this.createTableOfContentsPlaceholder();

    console.log('[PDF] Creating pre-installation elevation photos section...');
    await this.createElevationsSectionByStage(data, 'pre', 'Pre-Installation Elevations');

    console.log('[PDF] Creating property sections...');
    await this.createPropertySections(data);

    console.log('[PDF] Creating post-installation elevation photos section...');
    await this.createElevationsSectionByStage(data, 'post', 'Post-Installation Elevations');

    console.log('[PDF] Creating appendix...');
    await this.createAppendix();

    console.log('[PDF] Updating table of contents...');
    this.updateTableOfContents();

    console.log('[PDF] Generating final blob...');
    const blob = this.doc.output('blob');
    const blobSizeMB = (blob.size / (1024 * 1024)).toFixed(2);
    const totalCompressionRatio = this.totalOriginalSize > 0
      ? ((1 - this.totalCompressedSize / this.totalOriginalSize) * 100).toFixed(1)
      : '0';

    console.log('[PDF] Report generation complete');
    console.log(`[PDF] Final PDF size: ${blobSizeMB} MB (${blob.size} bytes)`);
    console.log(`[PDF] Total image compression: ${totalCompressionRatio}% reduction`);

    return blob;
  }

  private async createCoverPage(data: PropertyReportData): Promise<void> {
    console.log('[PDF] Creating professional header...');

    this.doc.setFillColor(20, 29, 46);
    this.doc.rect(0, 0, this.pageWidth, 50, 'F');

    this.doc.setTextColor(255, 255, 255);
    this.doc.setFontSize(32);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('CapturePro', this.pageWidth / 2, 30, { align: 'center' });

    this.doc.setTextColor(0, 0, 0);
    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('General Installation Evidence Report', this.pageWidth / 2, 65, { align: 'center' });

    this.doc.setTextColor(0, 0, 0);
    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    const propertyTitle = data.property.property_name || 'Property Report';
    this.doc.text(propertyTitle, this.pageWidth / 2, 85, { align: 'center' });

    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(`Job Reference: ${data.property.job_reference}`, this.pageWidth / 2, 100, { align: 'center' });

    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'normal');

    const addressLines = [
      data.property.address_line1,
      data.property.address_line2,
      data.property.city,
      data.property.postcode,
    ].filter(Boolean);

    let yPos = 120;
    addressLines.forEach((line) => {
      this.doc.text(line || '', this.pageWidth / 2, yPos, { align: 'center' });
      yPos += 7;
    });

    yPos += 10;
    autoTable(this.doc, {
      startY: yPos,
      head: [],
      body: [
        ['Organisation', data.organisation.name],
        ['Installation Date', new Date(data.property.installation_date).toLocaleDateString('en-GB')],
        ['Installer', data.property.assigned_installer_name || 'Not assigned'],
        ['Measure Type', 'B3 Windows and Doors'],
        ['Generated', new Date(data.generatedAt).toLocaleString('en-GB')],
        ['Generated By', data.generatedBy.full_name],
      ],
      theme: 'plain',
      styles: {
        fontSize: 11,
        cellPadding: 4,
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 45 },
        1: { cellWidth: 110 },
      },
      margin: { left: this.margin },
    });

    if (data.elevationPhotos.length > 0) {
      const frontElevation = data.elevationPhotos.find((e) => e.elevation_label.toLowerCase().includes('front'));
      if (frontElevation) {
        console.log('[PDF] Loading front elevation photo:', frontElevation.photo_url);
        try {
          const compressed = await this.compressImage(frontElevation.photo_url, 1000, 0.7);
          const imgHeight = 60;
          const imgWidth = (compressed.width / compressed.height) * imgHeight;
          const xPos = (this.pageWidth - imgWidth) / 2;
          this.doc.addImage(compressed.dataUrl, 'JPEG', xPos, 240, imgWidth, imgHeight);
          console.log('[PDF] Front elevation photo loaded and compressed');
        } catch (error) {
          console.warn('[PDF] Failed to load front elevation photo:', error);
        }
      }
    }

    console.log('[PDF] Cover page complete');

    this.addPageNumber();
  }

  private createTableOfContentsPlaceholder(): void {
    this.doc.addPage();
    this.currentPage++;

    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Table of Contents', this.margin, 30);
  }

  private async createElevationsSectionByStage(
    data: PropertyReportData,
    stage: 'pre' | 'post',
    sectionTitle: string
  ): Promise<void> {
    const elevationsForStage = data.elevationPhotos.filter((e) => e.stage === stage);

    if (elevationsForStage.length === 0) {
      console.log(`[PDF] No ${stage} elevation photos to process`);
      return;
    }

    console.log(`[PDF] Creating ${stage} elevation photos section with`, elevationsForStage.length, 'photos');

    this.doc.addPage();
    this.currentPage++;

    this.doc.setFontSize(20);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(sectionTitle, this.margin, 30);
    this.tableOfContents.push({ title: sectionTitle, page: this.currentPage });

    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`${elevationsForStage.length} elevation photo(s)`, this.margin, 40);

    let yPos = 55;
    const photoHeight = 60;
    const photoWidth = 80;

    for (const elevation of elevationsForStage) {
      if (yPos > 230) {
        this.doc.addPage();
        this.currentPage++;
        this.addPageNumber();
        yPos = 30;
      }

      const reference = `A${this.appendixPhotos.length + 1}`;
      const photo = {
        id: elevation.id,
        file_url: elevation.photo_url,
        template_id: '',
        gps_lat: null,
        gps_lng: null,
        captured_at: elevation.created_at,
        template: {
          id: '',
          title: `${elevation.elevation_label} Elevation`,
          help_text: `Property elevation view - ${elevation.elevation_label}`,
          stage: stage,
          sort_order: 0,
          scope: 'property' as const,
        },
      };
      this.appendixPhotos.push({ photo, reference });

      console.log('[PDF] Loading elevation photo:', elevation.elevation_label);
      try {
        const compressed = await this.compressImage(elevation.photo_url, 800, 0.7);
        console.log('[PDF] Elevation photo loaded and compressed');

        const imgWidth = photoWidth;
        const imgHeight = (compressed.height / compressed.width) * photoWidth;
        const finalHeight = Math.min(imgHeight, photoHeight);
        const finalWidth = finalHeight < imgHeight ? (compressed.width / compressed.height) * finalHeight : imgWidth;

        this.doc.addImage(compressed.dataUrl, 'JPEG', this.margin, yPos, finalWidth, finalHeight);

        this.doc.setFontSize(11);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(`${elevation.elevation_label} Elevation`, this.margin + finalWidth + 5, yPos + 5);

        this.doc.setFont('helvetica', 'normal');
        this.doc.setFontSize(10);
        this.doc.setTextColor(100, 100, 100);
        this.doc.text(`Captured: ${new Date(elevation.created_at).toLocaleString('en-GB')}`, this.margin + finalWidth + 5, yPos + 12);
        this.doc.setTextColor(0, 175, 255);
        this.doc.text(`See Appendix ${reference}`, this.margin + finalWidth + 5, yPos + 18);
        this.doc.setTextColor(0, 0, 0);

        yPos += photoHeight + 10;
      } catch (error) {
        console.warn('[PDF] Failed to load elevation photo:', error);
        this.doc.setFontSize(10);
        this.doc.text(`${elevation.elevation_label} Elevation - Photo unavailable`, this.margin, yPos + 5);
        yPos += 15;
      }
    }

    this.addPageNumber();
  }

  private async createPropertySections(data: PropertyReportData): Promise<void> {
    console.log('[PDF] Processing', data.areas.length, 'areas');

    for (const area of data.areas) {
      if (area.openings.length === 0) continue;

      console.log('[PDF] Processing area:', area.area_name, 'with', area.openings.length, 'openings');

      this.doc.addPage();
      this.currentPage++;

      this.doc.setFontSize(20);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`${area.area_name}`, this.margin, 30);
      this.tableOfContents.push({ title: area.area_name, page: this.currentPage });

      this.doc.setFontSize(12);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(`${area.openings.length} opening(s)`, this.margin, 40);

      let yPos = 50;

      for (const opening of area.openings) {
        const openingTitle = `${opening.opening_type.charAt(0).toUpperCase() + opening.opening_type.slice(1)} ${opening.opening_number}`;
        console.log('[PDF] Processing opening:', openingTitle, 'with', opening.photos.length, 'photos');

        if (yPos > 250) {
          this.doc.addPage();
          this.currentPage++;
          this.addPageNumber();
          yPos = 30;
        }

        this.doc.setFontSize(16);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(openingTitle, this.margin, yPos);
        yPos += 10;

        const photosByStage = {
          pre: opening.photos.filter((p) => p.template?.stage === 'pre'),
          during: opening.photos.filter((p) => p.template?.stage === 'during'),
          post: opening.photos.filter((p) => p.template?.stage === 'post'),
        };

        for (const [stage, photos] of Object.entries(photosByStage)) {
          if (photos.length === 0) continue;

          console.log('[PDF] Processing', photos.length, 'photos for stage:', stage);

          if (yPos > 240) {
            this.doc.addPage();
            this.currentPage++;
            this.addPageNumber();
            yPos = 30;
          }

          this.doc.setFontSize(14);
          this.doc.setFont('helvetica', 'bold');
          const stageTitle = stage.charAt(0).toUpperCase() + stage.slice(1) + ' Installation';
          this.doc.text(stageTitle, this.margin, yPos);
          yPos += 8;

          for (const photo of photos) {
            if (yPos > 230) {
              this.doc.addPage();
              this.currentPage++;
              this.addPageNumber();
              yPos = 30;
            }

            const reference = `A${this.appendixPhotos.length + 1}`;
            this.appendixPhotos.push({ photo, reference });

            console.log('[PDF] Loading photo:', photo.template?.title || 'Untitled', 'URL:', photo.file_url);
            try {
              const compressed = await this.compressImage(photo.file_url, 800, 0.7);
              console.log('[PDF] Photo loaded and compressed');

              const photoHeight = 60;
              const photoWidth = 80;
              const imgWidth = photoWidth;
              const imgHeight = (compressed.height / compressed.width) * photoWidth;
              const finalHeight = Math.min(imgHeight, photoHeight);
              const finalWidth = finalHeight < imgHeight ? (compressed.width / compressed.height) * finalHeight : imgWidth;

              this.doc.addImage(compressed.dataUrl, 'JPEG', this.margin, yPos, finalWidth, finalHeight);

              this.doc.setFontSize(11);
              this.doc.setFont('helvetica', 'bold');
              this.doc.text(photo.template?.title || 'Photo', this.margin + finalWidth + 5, yPos + 5);

              this.doc.setFont('helvetica', 'normal');
              this.doc.setFontSize(9);
              const descText = photo.template?.help_text || '';
              const splitDesc = this.doc.splitTextToSize(descText, 80);
              this.doc.text(splitDesc, this.margin + finalWidth + 5, yPos + 12);

              this.doc.setFontSize(9);
              this.doc.setTextColor(100, 100, 100);
              let metaYPos = yPos + 12 + (splitDesc.length * 4);
              if (photo.gps_lat && photo.gps_lng) {
                const accuracyText = photo.gps_accuracy ? ` (±${Math.round(photo.gps_accuracy)}m)` : '';
                this.doc.setFont('helvetica', 'bold');
                this.doc.setTextColor(0, 0, 0);
                this.doc.text(`GPS:`, this.margin + finalWidth + 5, metaYPos);
                this.doc.setFont('helvetica', 'normal');
                this.doc.setTextColor(100, 100, 100);
                this.doc.text(`${photo.gps_lat.toFixed(6)}, ${photo.gps_lng.toFixed(6)}${accuracyText}`, this.margin + finalWidth + 12, metaYPos);
                this.doc.setTextColor(0, 100, 200);
                this.doc.textWithLink('View Map', this.margin + finalWidth + 5, metaYPos + 4, {
                  url: `https://www.google.com/maps?q=${photo.gps_lat},${photo.gps_lng}`
                });
                this.doc.setTextColor(100, 100, 100);
                metaYPos += 9;
              }
              this.doc.setFont('helvetica', 'normal');
              this.doc.text(`Captured: ${new Date(photo.captured_at).toLocaleString('en-GB')}`, this.margin + finalWidth + 5, metaYPos);
              this.doc.setTextColor(0, 175, 255);
              this.doc.text(`See Appendix ${reference}`, this.margin + finalWidth + 5, metaYPos + 5);
              this.doc.setTextColor(0, 0, 0);

              yPos += photoHeight + 10;
            } catch (error) {
              console.warn('[PDF] Failed to load photo:', error);
              this.doc.setFontSize(10);
              this.doc.text('Photo unavailable', this.margin, yPos + 5);
              yPos += 15;
            }
          }

          yPos += 5;
        }

        yPos += 10;
      }

      this.addPageNumber();
    }
  }

  private async createAppendix(): Promise<void> {
    if (this.appendixPhotos.length === 0) {
      console.log('[PDF] No appendix photos to process');
      return;
    }

    console.log('[PDF] Creating appendix with', this.appendixPhotos.length, 'photos');

    this.doc.addPage();
    this.currentPage++;

    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Appendix - Full Size Images', this.margin, 30);
    this.tableOfContents.push({ title: 'Appendix', page: this.currentPage });
    this.addPageNumber();

    for (const { photo, reference } of this.appendixPhotos) {
      console.log('[PDF] Processing appendix photo:', reference, photo.template?.title);

      this.doc.addPage();
      this.currentPage++;

      this.doc.setFontSize(16);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`Reference ${reference}`, this.margin, 20);

      this.doc.setFontSize(12);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(photo.template?.title || 'Photo', this.margin, 30);

      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(10);
      if (photo.template?.help_text) {
        const splitDesc = this.doc.splitTextToSize(photo.template.help_text, this.contentWidth);
        this.doc.text(splitDesc, this.margin, 37);
      }

      console.log('[PDF] Loading full-size appendix photo:', photo.file_url);
      try {
        const compressed = await this.compressImage(photo.file_url, 1200, 0.7);
        console.log('[PDF] Appendix photo loaded and compressed');
        const maxHeight = 200;
        const maxWidth = this.contentWidth;
        let imgHeight = maxHeight;
        let imgWidth = (compressed.width / compressed.height) * imgHeight;

        if (imgWidth > maxWidth) {
          imgWidth = maxWidth;
          imgHeight = (compressed.height / compressed.width) * imgWidth;
        }

        const xPos = (this.pageWidth - imgWidth) / 2;
        this.doc.addImage(compressed.dataUrl, 'JPEG', xPos, 50, imgWidth, imgHeight);

        const infoY = 50 + imgHeight + 10;
        this.doc.setFontSize(10);
        this.doc.setFont('helvetica', 'bold');
        let currentInfoY = infoY;
        if (photo.gps_lat && photo.gps_lng) {
          this.doc.setTextColor(0, 0, 0);
          this.doc.text(`GPS Location:`, this.margin, currentInfoY);
          this.doc.setFont('helvetica', 'normal');
          this.doc.setTextColor(100, 100, 100);
          const accuracyText = photo.gps_accuracy ? ` (Accuracy: ±${Math.round(photo.gps_accuracy)}m)` : '';
          this.doc.text(`${photo.gps_lat.toFixed(6)}, ${photo.gps_lng.toFixed(6)}${accuracyText}`, this.margin, currentInfoY + 5);
          this.doc.setTextColor(0, 100, 200);
          this.doc.textWithLink('Click to view on Google Maps', this.margin, currentInfoY + 10, {
            url: `https://www.google.com/maps?q=${photo.gps_lat},${photo.gps_lng}`
          });
          this.doc.setTextColor(100, 100, 100);
          currentInfoY += 16;
        }
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(0, 0, 0);
        this.doc.text(`Captured:`, this.margin, currentInfoY);
        this.doc.setFont('helvetica', 'normal');
        this.doc.setTextColor(100, 100, 100);
        this.doc.text(`${new Date(photo.captured_at).toLocaleString('en-GB')}`, this.margin + 20, currentInfoY);
        this.doc.setTextColor(0, 0, 0);
      } catch (error) {
        console.warn('[PDF] Failed to load appendix photo:', error);
        this.doc.text('Photo unavailable', this.margin, 60);
      }

      this.addPageNumber();
    }

    console.log('[PDF] Appendix complete');
  }

  private updateTableOfContents(): void {
    const tocPage = 2;
    this.doc.setPage(tocPage);

    let yPos = 45;
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'normal');

    for (const entry of this.tableOfContents) {
      if (yPos > 270) {
        this.doc.addPage();
        this.currentPage++;
        yPos = 30;
      }

      this.doc.text(entry.title, this.margin, yPos);
      this.doc.text(entry.page.toString(), this.pageWidth - this.margin - 10, yPos, { align: 'right' });

      const dots = '.'.repeat(Math.floor((this.contentWidth - this.doc.getTextWidth(entry.title) - 15) / 2));
      this.doc.setTextColor(150, 150, 150);
      this.doc.text(dots, this.margin + this.doc.getTextWidth(entry.title) + 2, yPos);
      this.doc.setTextColor(0, 0, 0);

      yPos += 8;
    }

    this.doc.setPage(tocPage);
    this.addPageNumber();
  }

  private addPageNumber(): void {
    this.doc.setFontSize(10);
    this.doc.setTextColor(150, 150, 150);
    this.doc.text(
      `Page ${this.doc.getCurrentPageInfo().pageNumber} of ${this.currentPage}`,
      this.pageWidth / 2,
      this.pageHeight - 10,
      { align: 'center' }
    );
    this.doc.setTextColor(0, 0, 0);
  }

  private loadImage(url: string, timeoutMs: number = 10000): Promise<HTMLImageElement> {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.crossOrigin = 'anonymous';

      const timeoutId = setTimeout(() => {
        img.src = '';
        reject(new Error(`Image load timeout after ${timeoutMs}ms: ${url}`));
      }, timeoutMs);

      img.onload = () => {
        clearTimeout(timeoutId);
        resolve(img);
      };

      img.onerror = (error) => {
        clearTimeout(timeoutId);
        reject(new Error(`Image load error: ${url}`));
      };

      img.src = url;
    });
  }

  private async compressImage(
    url: string,
    maxWidth: number,
    quality: number = 0.6,
    timeoutMs: number = 10000
  ): Promise<{ dataUrl: string; width: number; height: number; originalSize: number; compressedSize: number }> {
    const img = await this.loadImage(url, timeoutMs);

    const originalSize = img.src.length;
    this.totalOriginalSize += originalSize;

    let targetWidth = maxWidth;
    let targetHeight = (img.height / img.width) * targetWidth;

    if (img.width <= maxWidth) {
      targetWidth = img.width;
      targetHeight = img.height;
    }

    const canvas = document.createElement('canvas');
    canvas.width = targetWidth;
    canvas.height = targetHeight;

    const ctx = canvas.getContext('2d');
    if (!ctx) {
      throw new Error('Failed to get canvas context');
    }

    ctx.drawImage(img, 0, 0, targetWidth, targetHeight);

    const dataUrl = canvas.toDataURL('image/jpeg', quality);
    const compressedSize = dataUrl.length;
    this.totalCompressedSize += compressedSize;

    const compressionRatio = ((1 - compressedSize / originalSize) * 100).toFixed(1);
    console.log(
      `[PDF] Compressed image: ${img.width}x${img.height} -> ${targetWidth}x${targetHeight}, ` +
      `${(originalSize / 1024).toFixed(1)}KB -> ${(compressedSize / 1024).toFixed(1)}KB (${compressionRatio}% reduction)`
    );

    return {
      dataUrl,
      width: targetWidth,
      height: targetHeight,
      originalSize,
      compressedSize,
    };
  }
}

export async function generateCaptureProReport(data: PropertyReportData): Promise<Blob> {
  const generator = new CaptureProReportGenerator();
  return await generator.generateReport(data);
}

export const generatePAS2030Report = generateCaptureProReport;
